CREATE TABLE IF NOT EXISTS user_verifications(
    id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    code char(6) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE
);